

import type { UnitType, SpellType } from './types';
import { SwordIcon, BowIcon, ShieldIcon, FireballIcon, HealIcon, CrossbowIcon, AssassinIcon, BerserkerIcon, FrostMageIcon, PaladinIcon, DragonIcon, GolemIcon, LancerIcon, NecromancerIcon, SandwormIcon, EnchantressIcon, PrismGuardIcon, ImpIcon, MagmaElementalIcon, ValkyrieIcon, IceGiantIcon, FarmerIcon, TucTucTucSahurIcon, TralaleroTralalaIcon, BombardinoCrocodiloIcon, MusqueteerIcon, BomberIcon } from './components/Icons';

export const GAME_CONFIG = {
  BUDGET: 1000,
  BATTLEFIELD_WIDTH: 1334,
  BATTLEFIELD_HEIGHT: 750,
  PLACEMENT_ZONE_WIDTH: 550,
  SIMULATION_TICK_MS: 50,
};

// --- Spell Definitions ---
export const ALL_SPELL_TYPES: SpellType[] = [
  {
    id: 'lightning',
    name: 'Lightning',
    description: 'Strike a point with electric fury, damaging enemies in a small area.',
    purchaseCost: 0,
    battleCost: 40,
    radius: 60,
    unlockWorld: 1,
  },
  {
    id: 'heal',
    name: 'Heal',
    description: 'Restore health to your units in the target area.',
    purchaseCost: 800,
    battleCost: 30,
    radius: 80,
    unlockWorld: 2,
  },
  {
    id: 'rage',
    name: 'Rage',
    description: 'Enrage allies in the area, boosting speed and damage for a short time.',
    purchaseCost: 1200,
    battleCost: 25,
    radius: 90,
    unlockWorld: 3,
  },
  {
    id: 'shield',
    name: 'Shield',
    description: 'Grant a protective barrier to allies, reducing damage taken briefly.',
    purchaseCost: 1500,
    battleCost: 30,
    radius: 90,
    unlockWorld: 4,
  },
];

// --- Unit Definitions ---
// Note: Boss units are not available for purchase and are defined here for use in levels.
// Special units are unlocked via roulette and not direct purchase.
export const ALL_UNIT_TYPES: UnitType[] = [
  // Tier 1 - Unlocked by default / in World 1
  {
    id: 'melee',
    name: 'Knight',
    cost: 100,
    purchaseCost: 0, // Unlocked by default
    hp: 200,
    damage: 20,
    attackRange: 50,
    speed: 1.5,
    icon: SwordIcon,
    role: 'MeleeDPS',
    description: "A stalwart warrior, the Knight excels at holding the frontline and dealing consistent damage.",
    launchSound: 'sword-swing.wav',
    impactSound: 'sword-impact.wav',
  },
  {
    id: 'ranged',
    name: 'Archer',
    cost: 100,
    purchaseCost: 0,
    hp: 80,
    damage: 15,
    attackRange: 200,
    speed: 1.8,
    icon: BowIcon,
    role: 'RangedDPS',
    description: "Keeps a safe distance, raining arrows down on foes. Effective against slow, unarmored targets.",
    launchSound: 'arrow-shoot.wav',
    impactSound: 'arrow-impact.wav',
  },
  {
    id: 'tank',
    name: 'Guardian',
    cost: 150,
    purchaseCost: 350,
    unlockWorld: 1,
    hp: 400,
    damage: 10,
    attackRange: 45,
    speed: 1.2,
    icon: ShieldIcon,
    role: 'Tank',
    description: "A walking fortress. Soaks up immense damage, protecting more fragile units behind it.",
    launchSound: 'shield-bash.wav',
    impactSound: 'shield-impact.wav',
  },
  // Tier 2 - World 1 Unlocks
  {
    id: 'mage',
    name: 'Mage',
    cost: 250,
    purchaseCost: 500,
    unlockWorld: 1,
    hp: 100,
    damage: 30,
    attackRange: 180,
    speed: 1.6,
    icon: FireballIcon,
    role: 'RangedDPS',
    ability: 'AOE_DAMAGE',
    abilityRadius: 40,
    description: "Hurls fireballs that explode on impact, damaging all enemies in a small area.",
    launchSound: 'fireball-cast.wav',
    impactSound: 'fireball-impact.wav',
  },
  {
    id: 'cleric',
    name: 'Cleric',
    cost: 200,
    purchaseCost: 600,
    unlockWorld: 1,
    hp: 110,
    damage: 20, // Heal amount nerfed
    attackRange: 150,
    speed: 1.4,
    icon: HealIcon,
    role: 'Support',
    ability: 'HEAL',
    description: "A vital support unit that heals injured allies, keeping your army in the fight longer.",
    launchSound: 'heal-cast.wav',
    impactSound: 'heal-impact.wav',
  },
  {
    id: 'crossbowman',
    name: 'Crossbowman',
    cost: 150,
    purchaseCost: 400,
    unlockWorld: 1,
    hp: 100,
    damage: 25,
    attackRange: 220,
    speed: 1.7,
    icon: CrossbowIcon,
    role: 'RangedDPS',
    description: "Slower to fire than an archer, but packs a much heavier punch. Great for piercing armor.",
    launchSound: 'crossbow-shoot.wav',
    impactSound: 'crossbow-impact.wav',
  },
  // Tier 3 - World 1 Unlocks
  {
    id: 'assassin',
    name: 'Assassin',
    cost: 180,
    purchaseCost: 700,
    unlockWorld: 1,
    hp: 90,
    damage: 35,
    attackRange: 40,
    speed: 2.5,
    icon: AssassinIcon,
    role: 'MeleeDPS',
    description: "Moves swiftly to bypass frontlines and eliminate high-value targets like Mages and Clerics.",
    launchSound: 'dagger-swing.wav',
    impactSound: 'dagger-impact.wav',
  },
   {
    id: 'lancer',
    name: 'Lancer',
    cost: 220,
    purchaseCost: 750,
    unlockWorld: 1,
    hp: 250,
    damage: 25,
    attackRange: 60,
    speed: 2.2,
    icon: LancerIcon,
    role: 'MeleeDPS',
    description: "Charges into battle with a powerful initial strike, breaking enemy formations.",
    launchSound: 'lance-charge.wav',
    impactSound: 'lance-impact.wav',
  },
  {
    id: 'farmer',
    name: 'Farmer',
    cost: 40,
    purchaseCost: 200,
    unlockWorld: 1,
    hp: 55,
    damage: 6,
    attackRange: 40,
    speed: 1.8,
    icon: FarmerIcon,
    role: 'Swarm',
    description: 'Not much of a fighter, but cheap and numerous. A true man of the soil.',
    launchSound: 'pitchfork-swing.wav',
    impactSound: 'pitchfork-impact.wav',
  },
  // Tier 4 - World 2 Unlocks
  {
    id: 'berserker',
    name: 'Berserker',
    cost: 300,
    purchaseCost: 1000,
    unlockWorld: 2,
    hp: 180,
    damage: 30,
    attackRange: 45,
    speed: 2.0,
    attackCooldown: 800,
    icon: BerserkerIcon,
    role: 'MeleeDPS',
    ability: 'RAGE',
    description: "A furious warrior who attacks faster and faster as the battle rages on.",
    launchSound: 'axe-swing.wav',
    impactSound: 'axe-impact.wav',
  },
  {
    id: 'frost_mage',
    name: 'Frost Mage',
    cost: 300,
    purchaseCost: 1200,
    unlockWorld: 2,
    hp: 130,
    damage: 15,
    attackRange: 170,
    speed: 1.6,
    icon: FrostMageIcon,
    role: 'Support',
    ability: 'SLOW',
    abilityRadius: 50,
    description: "Casts bolts of ice that slow enemies in an area, controlling the battlefield's pace.",
    launchSound: 'ice-cast.wav',
    impactSound: 'ice-impact.wav',
  },
  {
    id: 'paladin',
    name: 'Paladin',
    cost: 350,
    purchaseCost: 1500,
    unlockWorld: 2,
    hp: 450,
    damage: 15, // Self-heal amount
    attackRange: 50,
    speed: 1.3,
    icon: PaladinIcon,
    role: 'Tank',
    ability: 'SELF_HEAL',
    description: "A holy warrior blessed with resilience. Periodically heals itself during combat.",
    launchSound: 'hammer-swing.wav',
    impactSound: 'heal-impact.wav', // Re-uses heal sound
  },
  {
    id: 'sandworm',
    name: 'Sandworm',
    cost: 200,
    purchaseCost: 900,
    unlockWorld: 2,
    hp: 150,
    damage: 28,
    attackRange: 40,
    speed: 2.3,
    icon: SandwormIcon,
    role: 'MeleeDPS',
    isFlying: true, // It "burrows", functionally equivalent to flying
    description: "Burrows under the earth to bypass obstacles and frontline units, striking at the enemy's core.",
    launchSound: 'sand-emerge.wav',
    impactSound: 'sand-bite.wav',
  },
  {
    id: 'golem',
    name: 'Golem',
    cost: 400,
    purchaseCost: 1600,
    unlockWorld: 2,
    hp: 600,
    damage: 35,
    attackRange: 60,
    speed: 1.0,
    icon: GolemIcon,
    role: 'Tank',
    description: "A colossal stone behemoth. Extremely slow but unbelievably tough to take down.",
    launchSound: 'rock-fist.wav',
    impactSound: 'rock-impact.wav',
  },
  {
    id: 'necromancer',
    name: 'Necromancer',
    cost: 300,
    purchaseCost: 1400,
    unlockWorld: 2,
    hp: 120,
    damage: 0, // Doesn't attack directly
    attackRange: 150,
    speed: 1.5,
    attackCooldown: 5000,
    icon: NecromancerIcon,
    role: 'Support',
    ability: 'SUMMON',
    summonedUnitId: 'skeleton',
    description: 'Raises frail skeletons from the ground to fight for your cause. The more, the merrier.',
    launchSound: 'summon-cast.wav',
  },
  // Tier 5 - World 3 Unlocks
  {
    id: 'enchantress',
    name: 'Enchantress',
    cost: 320,
    purchaseCost: 1800,
    unlockWorld: 3,
    hp: 140,
    damage: 1.2, // 20% damage buff
    attackRange: 160,
    speed: 1.6,
    icon: EnchantressIcon,
    role: 'Support',
    ability: 'DAMAGE_AURA',
    description: "Doesn't attack, but empowers nearby allies with an aura, increasing their damage.",
    impactSound: 'aura-pulse.wav',
  },
  {
    id: 'prism_guard',
    name: 'Prism Guard',
    cost: 280,
    purchaseCost: 1700,
    unlockWorld: 3,
    hp: 350,
    damage: 20,
    attackRange: 50,
    speed: 1.4,
    icon: PrismGuardIcon,
    role: 'Tank',
    ability: 'REFLECT',
    description: 'A crystalline warrior that reflects a portion of damage taken back at its attackers.',
    launchSound: 'crystal-hit.wav',
    impactSound: 'crystal-shatter.wav',
  },
  {
    id: 'bomber',
    name: 'Bomber',
    cost: 170,
    purchaseCost: 1500,
    unlockWorld: 3,
    hp: 80,
    damage: 150, // Explosion damage
    attackRange: 40,
    speed: 2.4,
    attackCooldown: 100000, // Effectively doesn't attack
    icon: BomberIcon,
    role: 'MeleeDPS',
    ability: 'DEATH_BOMB',
    abilityRadius: 70, // Explosion radius
    isFlying: true,
    description: "A fast, flying unit that rushes towards enemies and explodes on death, dealing area damage.",
    impactSound: 'fireball-impact.wav', // Re-use explosion sound
  },
  {
    id: 'musqueteer',
    name: 'Musqueteer',
    cost: 200,
    purchaseCost: 900,
    unlockWorld: 1,
    hp: 55,
    damage: 85.8,
    attackRange: 650,
    speed: 1.6,
    attackCooldown: 11000,
    icon: MusqueteerIcon,
    role: 'RangedDPS',
    description: "A master sniper with unparalleled range. Fires an incredibly slow but devastating shot, capable of eliminating key targets from across the battlefield.",
    launchSound: 'musket-shot.wav',
    impactSound: 'musket-impact.wav',
  },
  // Tier 6 - World 4 Unlocks
  {
    id: 'imp',
    name: 'Imp',
    cost: 40,
    purchaseCost: 300,
    unlockWorld: 4,
    hp: 50,
    damage: 12,
    attackRange: 40,
    speed: 2.8,
    icon: ImpIcon,
    role: 'Swarm',
    description: 'A small, fast, and cheap demonic creature. Overwhelms enemies with sheer numbers.',
    launchSound: 'imp-attack.wav',
    impactSound: 'small-hit.wav',
  },
  {
    id: 'magma_elemental',
    name: 'Magma Elemental',
    cost: 380,
    purchaseCost: 1900,
    unlockWorld: 4,
    hp: 400,
    damage: 10, // Burn damage per second
    attackRange: 80,
    speed: 1.3,
    icon: MagmaElementalIcon,
    role: 'Tank',
    ability: 'DAMAGE_AURA',
    description: 'A walking inferno that constantly burns all nearby enemies.',
    impactSound: 'burn-crackle.wav',
  },
  // Tier 7 - World 5 Unlocks
  {
    id: 'valkyrie',
    name: 'Valkyrie',
    cost: 300,
    purchaseCost: 2000,
    unlockWorld: 5,
    hp: 180,
    damage: 30,
    attackRange: 50,
    speed: 2.0,
    icon: ValkyrieIcon,
    role: 'MeleeDPS',
    isFlying: true,
    description: 'A winged warrior who flies over obstacles and ground units to strike at the heart of the enemy.',
    launchSound: 'wing-flap.wav',
    impactSound: 'sword-impact.wav',
  },
  {
    id: 'ice_giant',
    name: 'Ice Giant',
    cost: 450,
    purchaseCost: 2200,
    unlockWorld: 5,
    hp: 550,
    damage: 40,
    attackRange: 70,
    speed: 1.1,
    icon: IceGiantIcon,
    role: 'Tank',
    ability: 'SLOW',
    abilityRadius: 70,
    description: 'A massive giant whose ground-pounding attacks slow all nearby enemies.',
    launchSound: 'stomp.wav',
    impactSound: 'ice-shatter.wav',
  },
  // Boss Units (Not Purchasable)
  {
    id: 'dragon_boss',
    name: 'Ancient Dragon',
    cost: 5000,
    hp: 2500,
    damage: 60,
    attackRange: 250,
    speed: 1.2,
    icon: DragonIcon,
    role: 'Boss',
    ability: 'AOE_DAMAGE',
    abilityRadius: 60,
    isFlying: true,
    description: 'A legendary beast of immense power.',
    launchSound: 'dragon-roar.wav',
    impactSound: 'fireball-impact.wav',
  },
  {
    id: 'boss_grove_guardian',
    name: 'Grove Guardian',
    cost: 4000,
    hp: 3000,
    damage: 40,
    attackRange: 70,
    speed: 1.0,
    attackCooldown: 2000,
    icon: GolemIcon,
    role: 'Boss',
    ability: 'SUMMON',
    summonedUnitId: 'sapling',
    description: "An ancient protector of the forest.",
    launchSound: 'stomp.wav',
    impactSound: 'rock-impact.wav',
  },
  {
    id: 'boss_dune_horror',
    name: 'Dune Horror',
    cost: 4500,
    hp: 2800,
    damage: 50,
    attackRange: 50,
    speed: 2.0,
    icon: SandwormIcon,
    role: 'Boss',
    isFlying: true, // Burrowing
    description: "A terrifying predator of the deep desert.",
    launchSound: 'sand-emerge.wav',
    impactSound: 'sand-bite.wav',
  },
  {
    id: 'boss_crystal_monstrosity',
    name: 'Crystal Monstrosity',
    cost: 5000,
    hp: 2200,
    damage: 30,
    attackRange: 60,
    speed: 1.3,
    icon: PrismGuardIcon,
    role: 'Boss',
    ability: 'REFLECT',
    description: "A colossal being of living, razor-sharp crystal.",
    launchSound: 'crystal-hit.wav',
    impactSound: 'crystal-shatter.wav',
  },
  {
    id: 'boss_magma_colossus',
    name: 'Magma Colossus',
    cost: 5200,
    hp: 3500,
    damage: 25, // Aura damage
    attackRange: 100, // Aura range
    speed: 0.9,
    icon: MagmaElementalIcon,
    role: 'Boss',
    ability: 'DAMAGE_AURA',
    description: "The molten heart of the volcano, given form.",
    impactSound: 'burn-crackle.wav',
  },
  // Summoned Unit (Not Purchasable or placable)
  {
    id: 'skeleton',
    name: 'Skeleton',
    cost: 0,
    hp: 30,
    damage: 8,
    attackRange: 40,
    speed: 1.7,
    icon: SwordIcon, // Re-use icon for simplicity
    role: 'Swarm',
    summonedUnitId: 'self', // Prevents it from being added to selection bars
    description: "A fragile warrior raised from the dead.",
    launchSound: 'sword-swing.wav',
    impactSound: 'bone-crack.wav',
  },
  
  // Special Roulette Units
  {
    id: 'tuc_tuc_tuc_sahur',
    name: 'Tuc Tuc Tuc Sahur',
    cost: 500,
    purchaseCost: 99999, // Effectively blocks purchase
    unlockWorld: 99,
    hp: 150,
    damage: 18,
    attackRange: 50,
    speed: 2.0,
    icon: TucTucTucSahurIcon,
    role: 'MeleeDPS',
    description: "It goes tuc tuc tuc. Then it goes sahur. A truly fearsome foe of unknown origin.",
    launchSound: 'tuc-sfx.wav',
    impactSound: 'tuc-impact.wav'
  },
  {
    id: 'tralalero_tralala',
    name: 'Tralalero Tralala',
    cost: 600,
    purchaseCost: 99999,
    unlockWorld: 99,
    hp: 200,
    damage: 0,
    attackRange: 50,
    speed: 1.8,
    attackCooldown: 500,
    icon: TralaleroTralalaIcon,
    role: 'Support',
    ability: 'BITE',
    abilityRadius: 50,
    description: "Locks onto a foe and bites it, dealing small DPS and disabling it briefly.",
    launchSound: 'tralala-song.wav',
    impactSound: 'aura-pulse.wav'
  },
  {
    id: 'bombardino_crocodilo',
    name: 'Bombardino Crocodilo',
    cost: 700,
    purchaseCost: 99999,
    unlockWorld: 99,
    hp: 300,
    damage: 40,
    attackRange: 160,
    speed: 1.4,
    icon: BombardinoCrocodiloIcon,
    role: 'RangedDPS',
    ability: 'AOE_DAMAGE',
    abilityRadius: 60,
    description: "Somehow, a crocodile learned to operate a bombard. The results are... explosive.",
    launchSound: 'bomb-throw.wav',
    impactSound: 'fireball-impact.wav'
  }
];

// --- Summoned/Special helper units ---
export const SAPLING_UNIT: UnitType = {
  id: 'sapling',
  name: 'Sapling',
  cost: 0,
  hp: 45,
  damage: 10,
  attackRange: 45,
  speed: 1.9,
  icon: SwordIcon,
  role: 'Swarm',
  launchSound: 'branch-swing.wav',
  impactSound: 'wood-hit.wav',
  summonedUnitId: 'self'
};

// Ensure ALL_UNIT_TYPES includes the sapling so it can be found by id for summoning
ALL_UNIT_TYPES.push(SAPLING_UNIT);